name: Test
on:
  push:

jobs:
  test:
    name: Debian
    strategy:
      matrix:
        go: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    container: debian:stable
    steps:
    - name: Install build dependencies
      run: |
        apt-get update
        apt-get install -y gcc git curl
    - name: Install go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Go unit test
      run: |
        cd build
        ./cmd test
    - run: pwd
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        file: ./build/cover.out
        flags: unittests
        fail_ci_if_error: true
    - name: Cache downloaded modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
